### ISSUE TITLE
Make using real ASIN an option

### ISSUE THREAD

**Issue by szarroug3** [szarroug3/X-Ray_Calibre_Plugin#19]
Currently, we use a custom format for the ASIN -- {calibre_id}_{book_format}. This stops kindle from replacing the book cover on the kindle with one downloaded from Amazon.

Some people may prefer having kindle download the cover from Amazon while others like picking custom covers in Calibre and using those. In the case of the former, we want to use the ASIN to the real ASIN retrieved from Amazon. In the case of the latter, we want to use the custom format shown above.

**Comment by szarroug3** [comment]
Problems that might arise doing this:

- If someone has the option to use real ASIN checked, creates the x-ray, then later unchecks the option, and creates startActions, endActions, and the author profile, the book will be updated to use the custom format. This will break the link to the x-ray they created before.
     - Maybe we can fix this by checking for an x-ray in the sdr and updating the ASIN in it to use what we're using for the new file.

- If we allow using the real ASIN, we will not be able to create multiple x-rays for different formats of the same book. For example, if someone has A Christmas Carol in both azw3 and mobi on the kindle and they try to create an x-ray and send it to the device for both formats, the x-ray file name would be the same for both formats and would need to reside in the same directory.

**Comment by szarroug3** [comment]
@stoduk thoughts?

**Comment by stoduk** [comment]
First, I hadn't realised the need for this fix (ie. that Kindle will just overwrite a perfectly good thumbnail, if the ASIN is a regular one) - but a quick test confirms that is happening.  Odd behaviour - why would it look for a new thumbnail if one was already there?  How does it know when it needs to check for a new one?

[obviously this means this is a problem for the windows GUI as well - surprised people haven't grumbled there too, perhaps they have and I've missed it..]

Anyway - given the behaviour, I imagine a lot of people would like to use the artwork from Calibre, rather than having Kindle choosing.  Making it an option seems reasonable - as long as there is an explanation of why you'd want to choose one vs. the other.

re. the problem you mentioned - I think this would just be a bug.  THe problem exists there now, namely:
- copy book in Calibre
- generate Xray
- copy xray (which does the ASIN tweaking)
- (optionally modify book and) recopy book in Calibre
--> we've got a book that doesn't match the Xray files, and we think because there is an Xray file there we have nothing to do.

I'd be surprised if anyone chooses to have the same book in multiple formats on their device - what are you imagining the use-case would be there?


So currently my thinking is:
- let user choose between "{ASIN}" or "{ASIN}_{format}" for the ASIN
- modify the ASIN *in Calibre database*.  This removes one possible mismatch problem, and I can't see anyone caring what this value actually is (people only set ASIN to get XRAY to work, which we are doing!).
- be a little more careful choosing whether to copy xray/start actions/etc. - ie. don't just look for existence of a file, perhaps doing a full diff to decide if it needs updating [we could just update always, but being a flash device it might be good to avoid unnecessary writes]

**Comment by szarroug3** [comment]
Yeah, I don't know why it forces the download of a new thumbnail. It only happens when you put a real ASIN in the book though. I haven't seen anyone complain about this before. I noticed it when I was testing. I'm not sure why I didn't notice it before.

As for the mismatch, if we don't give them an option, it shouldn't happen because when we're sending the file, the plugin looks at the book and checks what the value is. Then it updates it to add the format to the end. It uses that value for the filename. So maybe we just have the action files use that value.

**Comment by stoduk** [comment]
Not sure if we are talking at cross purposes re. the mismatch.  The problem I see is if you copy the book after copying the X-Ray data, you'll overwrite the book on the Kindle (so it now has whatever the ASIN was originally set to, without _mobi or whatever) - and even if you told the plugin to send the XRay over again it wouldn't copy (look for 'device_xray_files' in book.py - if xray files are found and overwrite is not set, which is only set on a create not a copy command, then we'll not update the Xray - yet we needed to).

This is obviously just a bug in the current code rather than something fundamentally wrong - just wanted to make sure it wasn't ignored.  A quick check of the two files and (always) copying if they differ would seem sensible - ie. get rid of the difference in 'overwrite' behaviour between the create/send codepaths, and always do whatever is needed.

Does that make sense?

**Comment by szarroug3** [comment]
Yeah, I see what you're saying. In that case, you're right about updating
the database as well. Can you take this issue?

**Comment by szarroug3** [comment]
So do we both agree that most people don't really cares about the book having the real ASIN or not? If so, I think we can just close this out and if anyone really has heartburn over it, they can just tell us and we can deal with it then.

**Comment by stoduk** [comment]
I'm happy to close it for now, things working seems more important to me than how they work :)
