### ISSUE TITLE
Parse out "aka's" from description in ShelfariParser

### ISSUE THREAD

**Issue by szarroug3** [szarroug3/X-Ray_Calibre_Plugin#30]
I'm not really sure how to do this because I don't know how to know where the end of the name would be. i.e John Doe - aka Jake. Jake is a tall man. vs ie. John Doe - aka Jake Doe. Jake is a tall man.

We could look for the punctuation at the end of the aka but we can't really guarantee that that will always be there.

**Comment by stoduk** [comment]
I'm a bit hazy, but from the comment I put in the old plugin I think we
expect

"Jane McGuiness (aka Jane Maidenname)"

    aka_regex = re.compile("(.*) +\(aka.? (.*)\)")

However, ISTR that this was free form - ie. whatever the user edited when
they added the aka, rather than the website generating this from a list of
aliases.  So it looks like I thought it was always in parenthesis, and
sometimes has a period after "aka".

Almost certainly a fix where we'll keep tweaking as we find new ways it can
be broken :)

**Comment by szarroug3** [comment]
I don't think this is needed anymore -- Goodreads has aliases built-in
