### ISSUE TITLE
Hard disk error

### ISSUE THREAD

**Issue by redebs** [szarroug3/X-Ray_Calibre_Plugin#34]
I'm running calibre 2.53 64bit on Windows 7. It runs locally and files are on the same drive my system runs on.

I'll select a book and select Create/Update X-Rays. It will parse the data then this error will always pop up regardless if my kindle is connected or not:

> There is no disk in the drive. Please insert a disk into \Device\Harddisk1\DR1

I found that clicking 'Try Again' or 'Continue' exactly four times and it works.

This is the log I get on the Creating X-Ray Files job:

> Starting job: Creating X-Ray Files 
>  
> 05-31-2016 18:49:39 Night Film - Marisha Pessl 
> 05-31-2016 18:49:39 	Parsing shelfari data... 
> 05-31-2016 18:49:41 	Getting format specific data... 
> 05-31-2016 18:49:41 	Parsing book data... 
> 05-31-2016 18:49:45 	Creating x-ray... 
> 05-31-2016 18:49:46 	Sending x-ray to device... 
> 
> X-Ray Creation: 
> 	Books Completed: 
> 		Night Film - Marisha Pessl: AZW3 
> 
> X-Ray Sending: 
> 	Books Failed: 
> 		Night Film - Marisha Pessl: 
> 			AZW3: The book is not on the device. 

The book is on the device connected.

**Comment by stoduk** [comment]
Thanks @redebs - @szarroug3 I think you'll have to take this one as it is definitely Windows related :)

I can't see the error string in the plugin or Calibre code anywhere.  I've found lots of mentions on the internet of problems with similar error text, nobody seems to have said anything too definitive.  Mentions of Calibre installs on temporary media exists, though @redebs is running it locally so that doesn't apply here.

@redebs - is your Calibre "installed" (in "Program Files" or similar) or just being run from elsewhere on your hard drive?

At first thoughts my suspicion rests in the windll that python uses on Windows..

**Comment by redebs** [comment]
@stoduk yes, Calibre is installed in "Program Files." I didn't change the default path when I installed Calibre. 

I found out that others have this error too when I checked the forums but nobody had any fix (yet) other than clicking the buttons a couple of times.

**Comment by stoduk** [comment]
@redebs - two questions:
1) is the error from calibre, or is this a windows dialog box?

2) do you have an empty removeable drive?  eg. a card reader without a card, optical drive without a disk?  I suspect if you put a drive in every available removeable drive then you'd see this error go away.

@szarroug3 - see this link.  I think the problem is because you are accessing empty removable drives, and this is popping up an error.  See the details in the thread below on how to fix this - no point me doing it as I can't test it!

http://stackoverflow.com/questions/29059399/searching-for-a-usb-in-python-is-returning-there-is-no-disk-in-drive

**Comment by redebs** [comment]
@stoduk 
1) Calibre
2) No, there is no removable drive/card reader/optical drive/external hard disk connected on the computer. The only devices connected now are: wireless mouse/keyboard and usb wifi adaptor.

**Comment by redebs** [comment]
@stoduk @szarroug3 I've tried a few times again and the hard disk error seems to have (temporarily?) disappeared. I didn't do/change anything since the last error happened. Weird.

**Comment by szarroug3** [comment]
@stoduk Yeah it's Windows. At first glance, it looked like Linux to me since the drive was \Device\Harddisk1\DR1. That's a bit confusing haha. I'll take it on.

Since it seems like it's always exactly 4 times, it's probably finding 4 "empty" drives. I'll create a zip with an experimental fix since I can't seem to recreate the issue myself. @redebs if you can install the plugin from the zip I give you and test it then report back, that would be great!

**Comment by redebs** [comment]
@szarroug3 sure thing! 

It's really weird though that the error seems to have resolved itself since I've tried it with over 20 books now and haven't been able to replicate it again. The only real caveat now is that I still have to manually copy the .asc files to my kindle ppw since the plugin can't seem to find the specified book on the device.

**Comment by szarroug3** [comment]
@redebs Here's the zip: [2.1.2](https://github.com/szarroug3/X-Ray_Calibre_Plugin/blob/dev/no_hard_disk_fix_experimental/Versions/xray_creator_calibre_plugin_2_1_2.zip?raw=true)

If you can recreate the original problem with 2.1.1 then try to run it with 2.1.2, that would be optimal. That way we'll know that the fix is what fixed it.

**Comment by redebs** [comment]
@szarroug3 installed 2.1.2 got the hard disk error again. Reverted back to 2.1.1, all is fine again. 

Maybe post this version to the forum so other people who experienced the same hard disk error as me can double check? I'm sorry, but think my computer is playing mind games with me haha

**Comment by redebs** [comment]
@szarroug3 I installed 2.1.2 got the hard disk error. Reverted back to a previous Calibre backup with 2.1.1, worked properly with 1 book then got the hard disk error again.

I deleted my previous comment to avoid confusion.

**Comment by stoduk** [comment]
@szarroug3 - just a thought: assuming that link is right, and the problem is that we are accessing an empty removable drive, then could we filter the drives in `_get_drive_info` using output from "wmic logicaldisk get name,size" or similar?  In the output below D: is an empty (virtual) CD drive - I don't think the virtualness matters though.

@redebs - what output do you get if you run this command?
```
C:\>wmic logicaldisk get name,size
Name  Size
C:    26736586752
D:
E:    249199591424
F:    249199591424
R:    249199591424
W:    249199591424
```

**Comment by szarroug3** [comment]
@redebs Sorry just realized I missed a comment. For it not finding the book on the device, it's probably that Calibre is putting the book somewhere other than the place where the plugin is expecting it to be. The plugin expects it the book to be at {Author Sort}\{Book Name} - {Author} -- if it's getting put somewhere else, that's the issue. There's an open issue about this already here: https://github.com/szarroug3/X-Ray_Calibre_Plugin/issues/28 if you want to subscribe to that thread.

**Comment by redebs** [comment]
@stoduk 

> C:\Users\Administrator>wmic logicaldisk get name,size
>Name  Size
>C:    1000202039296
>D:
>E:
>F:
>G:
>H:
>I:
>J:
>U:

@szarroug3 thanks man. I'll check this out tomorrow.

**Comment by stoduk** [comment]
What are all the drives that aren't C:?  I suspect they are what is causing the glitch..

**Comment by redebs** [comment]
@stoduk I have no clue. I actually only have one drive connected (C:) 
I don't know where those drives even came from haha

**Comment by stoduk** [comment]
So you don't see these in Windows Explorer?  Strange!  I don't use Windows
much these days, so no idea what this means :)

**Comment by redebs** [comment]
I don't! Where did those even come from? Would be a nice surprise though to find a few drives connected for free! One can only dream :)
On the other hand, I can only survive on Windows haha. Btw, thanks for all the help mate.

**Comment by szarroug3** [comment]
I think they're available drives. My CD drive shows up as D even when there's no disk in there so I assume it means those are open slots that get automatically mapped when you plug something in. They've probably changed the way windows handles empty drives since the only empty one that shows up for me is D but you have many more. I'm looking into this today.

**Comment by szarroug3** [comment]
Also, I've created a gitter.im chatroom for this repo. Think it might make it easier to communicate when we're actively talking about things instead of posting comments. Here's the link: [https://gitter.im/szarroug3/X-Ray_Calibre_Plugin]( https://gitter.im/szarroug3/X-Ray_Calibre_Plugin )

**Comment by szarroug3** [comment]
Found this [stackoverflow ](http://stackoverflow.com/questions/4188326/in-python-how-do-i-check-if-a-drive-exists-w-o-throwing-an-error-for-removable) page that says the error is caused by the computer assigning a drive letter to a drive that doesn't exist. I applied the fix they suggested. @redebs , can you test it? Here's the [zip](https://github.com/szarroug3/X-Ray_Calibre_Plugin/blob/dev/no_hard_disk_fix_experimental/Versions/xray_creator_calibre_plugin_2_1_3.zip?raw=true).

**Comment by redebs** [comment]
@szarroug3 I just tested 2.1.3 and still got the same hard disk error on all four books I tried it with. 
>There is no disk in the drive. Please insert a disk into \Device\Harddisk1\DR1
Click "Try Again" or "Continue"
>There is no disk in the drive. Please insert a disk into \Device\Harddisk1\DR2
Click "Try Again" or "Continue"
>There is no disk in the drive. Please insert a disk into \Device\Harddisk1\DR3
Click "Try Again" or "Continue"
>There is no disk in the drive. Please insert a disk into \Device\Harddisk1\DR4
Click "Try Again" or "Continue"
Then it works.

I'll be reverting to the newly released 2.1.2 with the fix @stoduk introduced for https://github.com/szarroug3/X-Ray_Calibre_Plugin/issues/32.

Cool idea with the chatroom! Sadly, I don't have much time to chat today as I have tons of errands to run.

**Comment by stoduk** [comment]
So the change is to switch ctypes.windll.kernel32.GetLogicalDrive() to ctypes.cdll... ?  Windows is odd :)

If that doesn't work then PolyMesh's suggestion is similar to what I was suggesting, he just passes through different args (I think if we go with getting name,size and filter out anything without a size we should be safe.  Can get the type as well if you want to differentiate internal vs. removable).

**Comment by stoduk** [comment]
Overlapping comments!  Seems like windows offers two ways of doing the same thing, neither of which work :)

**Comment by szarroug3** [comment]
@redebs, are you seeing that on a command line or something? Just curious
since it seems like you're copying and pasting. I'm thinking I could print
some test statements somewhere to see exactly which call is making it
happen.

@stoduk, yeah windows is definitely odd.. I'm actually not 100% sure what
the exact difference. I'll looking to a way to do wmic using Python after
lunch.. I think the problem is when we're getting the logical drives, it's
getting the complete list before filtering and giving us the result and
that's what causing the error.

**Comment by redebs** [comment]
@stoduk The error is in a windows dialog box. I previously thought the error was in Calibre but upon double checking, it's on windows. Sorry for the confusion, @szarroug3. 

Here's a screenshot of the error:
![hderror](https://cloud.githubusercontent.com/assets/19311334/15719240/a1994be4-2861-11e6-9d41-c48079496221.png)
