### ISSUE TITLE
add support for goodreads

### ISSUE THREAD

**Issue by szarroug3** [szarroug3/X-Ray_Calibre_Plugin#4]
Add support to get x-ray data from Goodreads -- may put this off for now. Goodreads doesn't have that much information yet -- waiting to see if Goodreads starts to get more information.. For now, it only has characters for a few locations. It would be nice to switch to Goodreads since shelfari is so slow.

**Comment by stoduk** [comment]
Also: see request on the forum for adding a Russian source (http://livelib.ru, see http://www.mobileread.com/forums/showpost.php?p=3319610&postcount=73).

So adding a series of plugins, and letting the user pick, would seem like a decent idea.  Though good luck figuring out how to parse a Cyrillic website :)

**Comment by szarroug3** [comment]
I'm all for adding more sources. I looked at livelib. It doesn't have
character or term descriptions. I'm not sure what exactly he wanted us to
do with it. Maybe I'm missing something considering how I'm just reading
the translation of the website.

**Comment by stoduk** [comment]
Ha, I hadn't checked that (because Chrome's auto-translate had a paddy) -
but that would be a major stumbling block!

**Comment by szarroug3** [comment]
Haha, yeah I had to get it to manually translate. Anyways, yeah I'll
respond on mobileread . Maybe he doesn't know exactly what x-ray does.

**Comment by szarroug3** [comment]
This is now a blocker. Shelfari has officially started redirecting to Goodreads. The plugin is basically useless as it is now. This shouldn't be too hard to do but the problem is that Goodreads doesn't have the data but there's nothing we can do about that.

**Comment by stoduk** [comment]
Damn it!  Guess we knew this would come eventually.  I don't think Goodreads has any intention on merging the character data they have from Shelfari (see https://www.goodreads.com/topic/show/17975774-shelfari-merger, they tried already hit problems and I assume gave up).

So the two options I can think of are Goodreads.com and Librarything.com.  Both have the same two flaw - character information is stored on a separate page (not a deal breaker, just slower to fetch), and the information is for the character across all books (which makes it far less useful for long running series - making it relevant from the first to the last book must limit what can be said without fear of spoilers).

Goodreads.com
+ amazon owned and seems fast enough
- we know amazon can throw the baby out with the bath water, so not a long term plan potentially
+ all edits have to be made by a "librarian", so less chance of spam or intentional garbage (Shelfari suffered the latter at least)
- all edits have to be made manually by a librarian, triggered by a forum request.  This has to be both slow and error prone, and I assume there will be limits to how many they'll allow.

librarything.com:
+ independent
- could still sell out as Shelfari did, and so still not guaranteed
- no history of edits, tracking of who made them, etc.  You do have to be logged in but that is a small protection

The only options that spring to mind are:
- wikipedia.  There is probably a page for each book anyway, so adding character data might fit.  The format can't be policed though, so more potential for either generous parsing or getting people to fixup the data when it is broken.  Generally they are independent and pro-information sharing, so from that side they are a good fit.
- new website. I had toyed with the idea of doing this, but it seems like a lot of work to fill the small hole the others have (ie. both add per-book character data, and give us some hope that the information submitted will be there indefinitely or at least exportable at will).  However, the simplest of simple websites perhaps wouldn't be too onerous, if using google app engine or similar.

Thoughts?  I'm tempted to think wikipedia is worth investigating..

**Comment by szarroug3** [comment]
I think I like the idea of Wikipedia but it doesn't seem to have quotes or
terms. I don't mind not having quotes but having terms was super important
to me when reading the mistborn trilogy. I'll look into it some more today.
I started converting to goodreads last night to try to get something
working while we figure this out. I'm surprised Amazon didn't at least
require the shelfari data be migrated before shutting down. I wonder what
they're going to use for x-rays now.

We can make a new website but that brings up a whole new host of trouble
--Where do we host it? Domain names aren't free so it'll be costing us.
Where do we get the information? If we get people to put it in, how do we
get people to use it? A lot of people seemed to like goodreads and shelfari
because of the bookshelf feature so do we implement that?

**Comment by szarroug3** [comment]
@stoduk I'll be on gitter today if you want to discuss. I found another potential plus for Goodreads -- if we use Goodreads to search, it has a link to the amazon page so we can use that rather than searching amazon for the book.

**Comment by szarroug3** [comment]
@stoduk Have you thought about this? I'm still not sure what I want to do :disappointed:

**Comment by szarroug3** [comment]
Finished in #41
