### ISSUE TITLE
Auto expand bug

### ISSUE THREAD

**Issue by szarroug3** [szarroug3/X-Ray_Calibre_Plugin#82]
We are removing aliases from the aliases list when we find a duplicate

i.e; if we have Harry Potter and Harry James Potter
Harry Potter would have the aliases Harry and Potter but then when Harry James Potter comes along and we find "Harry" as an alias again, we remove the whole alias from the list

we should be skipping this instead

**Comment by szarroug3** [comment]
@stoduk Any comments on this?

**Comment by stoduk** [comment]
Are you suggesting we have two characters here, with the same first/last names?  I'm assuming that in my thoughts below.

If we have Harry Potter and Harry James Potter, then I would expect the code to try expand both to "Harry" and "Potter" - but these clash so both will be dropped.  So we'll end up with just the original character names ("Harry Potter" and "Harry James Potter") for character detection, no aliases will be used.

I don't see how we can (automatically) do anything else.  We can't differntiate which "Harry" or "Potter" refers to which of the two characters, so we don't try.  If the user is sure that one is far more common (so the false matches are acceptable) then they could choose to manually add an alias.  

A good example of this is "Reacher" in the Jack Reacher books - I would imagine almost every reference to just Reacher would refer to him; all references to his family would either be by full name or just first name.  I know this, but the code can't possibly work that out.

**Comment by stoduk** [comment]
I've just seen commit #83 - and it seems that if you spot the duplicate you want to keep "Harry" and "Potter" as aliases for the first character we process, but not as an alias for the later "Harry James Potter".

I'm not sure why you think we'd want that behaviour - can you explain?  Perhaps give an example of where you think this will work in our favour, as if we think there are cases where it would then it might be worth doing.

The behaviour of this new commit seems to have some implicit assumption that we are processing characters in decreasing importance (or, at least, decreasing frequency in the book).  That seems to be an assumption that I'm not convinced will be true that often.  Imagine one of those epic family saga type books - Harry Potter is mentioned in the first part after which he dies; in the second part it is his son Harry James Potter who is mentioned.  We'll now be incorrectly assuming that all mentions of "Harry" throughout are for the guy from the first part, when it isn't.

My gut feeling is if we can't make be reasonably sure that we are making a good guess at which character a particular reference (such as "Harry") refers to then we just don't bother.  A reader is then likely to look closer and tweak the aliases used if *they* know that some assumption can be made (such as in my Reacher example).

All of this is, almost by design, imperfect.  If we want perfect character matching then we'll need to go down the route of hiring people to manually annotate every character reference in the book.  If people want that then they can probably just repurchase their books from Amazon :)

**Comment by szarroug3** [comment]
Hm, you're right. The reason I thought of it was because I know that Harry
Potter and Harry James Potter are, in fact, the same person. Harry James
Potter is actually added only because he's listed as Harry Potter's alias
on Goodreads so Harry Potter should actually have Harry James Potter,
Harry,  and Potter all as aliases. Guess we'll need to find a way to link
the alias to the original and then make the distinction.

**Comment by szarroug3** [comment]
@stoduk I've updated to reflect what we talked about; Also, I found that GR actually keeps multiple aliases in a comma separated list -- see here: [https://www.goodreads.com/characters/28278-lord-voldemort](https://www.goodreads.com/characters/28278-lord-voldemort)

And I've realized that we're not accounting for first name being a common word
i.e. "The Lord Ruler" should never have the aliases "The Ruler", "Ruler" or "Lord" but should have "Lord Ruler"

**Comment by szarroug3** [comment]
i'm going to merge.. if you come up with anything, we can make a new branch/pull request
